@echo off
set "ROOT=E:\Projetos\Android\Trililingo\app\src\main\java"
cd /d "%ROOT%" || exit /b 1
mkdir "com\trililingo\core\time"
mkdir "com\trililingo\data\db\daos"
mkdir "com\trililingo\data\db\entities"
mkdir "com\trililingo\data\datastore"
mkdir "com\trililingo\data\repo"
mkdir "com\trililingo\domain\engine"
mkdir "com\trililingo\python"
mkdir "com\trililingo\sync"
mkdir "com\trililingo\ui\design"
mkdir "com\trililingo\ui\nav"
mkdir "com\trililingo\ui\screens\home"
mkdir "com\trililingo\ui\screens\lesson"
mkdir "com\trililingo\ui\screens\result"
mkdir "com\trililingo\di"
type nul > "com\trililingo\TrililingoApp.kt"
type nul > "com\trililingo\MainActivity.kt"
type nul > "com\trililingo\core\time\TimeProvider.kt"
type nul > "com\trililingo\data\db\TrililingoDb.kt"
type nul > "com\trililingo\data\db\daos\ActivityAttemptDao.kt"
type nul > "com\trililingo\data\db\daos\LanguageItemDao.kt"
type nul > "com\trililingo\data\db\daos\SrsStateDao.kt"
type nul > "com\trililingo\data\db\daos\StudySessionDao.kt"
type nul > "com\trililingo\data\db\daos\SyncEventDao.kt"
type nul > "com\trililingo\data\db\entities\ActivityAttemptEntity.kt"
type nul > "com\trililingo\data\db\entities\LanguageItemEntity.kt"
type nul > "com\trililingo\data\db\entities\LanguageItemEntity.kt"
type nul > "com\trililingo\data\db\entities\SrsStateEntity.kt"
type nul > "com\trililingo\data\db\entities\StudySessionEntity.kt"
type nul > "com\trililingo\data\db\entities\SyncEventEntity.kt"
type nul > "com\trililingo\data\datastore\UserPrefsDataStore.kt"
type nul > "com\trililingo\data\repo\ContentSeeder.kt"
type nul > "com\trililingo\data\repo\StudyRepository.kt"
type nul > "com\trililingo\data\repo\UserPrefsRepository.kt"
type nul > "com\trililingo\domain\engine\ActivityEngine.kt"
type nul > "com\trililingo\domain\engine\ActivityModels.kt"
type nul > "com\trililingo\python\PythonSrsBridge.kt"
type nul > "com\trililingo\sync\SyncWorker.kt"
type nul > "com\trililingo\sync\SyncScheduler.kt"
type nul > "com\trililingo\ui\design\NeonTheme.kt"
type nul > "com\trililingo\ui\design\NeonWidgets.kt"
type nul > "com\trililingo\ui\nav\NavGraph.kt"
type nul > "com\trililingo\ui\screens\home\HomeViewModel.kt"
type nul > "com\trililingo\ui\screens\home\HomeScreen.kt"
type nul > "com\trililingo\ui\screens\lesson\LessonViewModel.kt"
type nul > "com\trililingo\ui\screens\lesson\LessonScreen.kt"
type nul > "com\trililingo\ui\screens\result\ResultScreen.kt"
type nul > "com\trililingo\di\AppModule.kt"
